# Generated by Django 4.1.7 on 2023-10-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=20)),
            ],
        ),
    ]
