# Generated by Django 4.1.7 on 2023-10-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webyops", "0002_resumedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate_Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("status", models.CharField(max_length=20)),
                ("comment", models.TextField()),
            ],
        ),
    ]
