# Generated by Django 4.1.7 on 2023-10-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webyops", "0005_services_delete_resumedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=500)),
            ],
        ),
    ]
