# Generated by Django 4.1.7 on 2023-10-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webyops", "0008_schedulemeeting_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("template_view", models.CharField(max_length=100)),
                ("action_type", models.CharField(max_length=15)),
                ("pdf_content", models.TextField()),
            ],
        ),
    ]
