# Generated by Django 4.1.7 on 2023-10-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webyops", "0009_personaldata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_JobId", models.CharField(max_length=255)),
                ("_JobRole", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("resume_csv", models.TextField()),
            ],
        ),
    ]
