# Generated by Django 4.1.7 on 2023-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webyops", "0012_todolist"),
    ]

    operations = [
        migrations.CreateModel(
            name="vendorFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=500)),
                ("vendor_type", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=500)),
                ("positionToApply", models.CharField(max_length=500)),
                ("referring_candidate", models.TextField()),
            ],
        ),
    ]
