# Generated by Django 4.1.7 on 2023-10-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webyops", "0013_vendorfollowup"),
    ]

    operations = [
        migrations.CreateModel(
            name="marketingCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=500)),
                ("personal_data", models.CharField(max_length=500)),
                ("resume", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=20)),
                ("comment", models.CharField(max_length=500)),
            ],
        ),
    ]
