# Generated by Django 4.1.7 on 2023-10-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webyops", "0014_marketingcandidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="scheduleMeetingRecrt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
