# Generated by Django 4.1.7 on 2023-10-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webyops", "0016_recrtdocumentation"),
    ]

    operations = [
        migrations.CreateModel(
            name="candidateSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=500)),
                ("visa_status", models.CharField(max_length=500)),
                ("gender", models.CharField(max_length=100)),
                ("technology", models.CharField(max_length=500)),
            ],
        ),
    ]
