# Generated by Django 4.1.7 on 2023-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file1", models.FileField(upload_to="uploads/")),
                ("file2", models.FileField(upload_to="uploads/")),
                (
                    "merged_result",
                    models.FileField(null=True, upload_to="merged_results/"),
                ),
            ],
        ),
    ]
