# Generated by Django 4.1.7 on 2023-10-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("excel_mining", "0002_csvdata"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CsvData",
            new_name="ExcelToCsv",
        ),
        migrations.RenameField(
            model_name="exceltocsv",
            old_name="name",
            new_name="sheet_id",
        ),
    ]
